# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SEED": "02_Optimizer.ipynb",
         "get_example_dataset": "00_core.ipynb",
         "ATMSKLEARN": "01_Representation.ipynb",
         "combine": "01_Representation.ipynb",
         "Instance": "01_Representation.ipynb",
         "Optimizer": "02_Optimizer.ipynb",
         "cost_matrix": "02_Optimizer.ipynb"}

modules = ["core.py",
           "tree.py",
           "optimizer.py"]

doc_url = "https://numb3r33.github.io/oae/"

git_url = "https://github.com/numb3r33/oae/tree/master/"

def custom_doc_links(name): return None
