# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['SEED', 'get_example_dataset', 'get_example_dataset']

# Cell
import numpy as np

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split as tts

SEED = 41
np.random.seed(SEED)

# Cell
def get_example_dataset():
    X, y = make_classification(n_samples = 100, n_features=5)
    Xtr, Xte, ytr, yte = tts(X, y, test_size=0.2, random_state=SEED)

    return Xtr, Xte, ytr, yte